### ISSUE TITLE
1.33.0: "File exists" errors when un-taring golangci-lint

### ISSUE THREAD

**Issue by andig** [golangci/golangci-lint-action#135]
I'm using the linter action in https://github.com/andig/evcc/pull/497/checks?check_run_id=1474850871:

Go artefacts are already cached:

    steps:
    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          **/node_modules
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-go-

    ...

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.33
        
This leads to large amount of errors in the action log:

    Installed Go in 79ms
    Requested golangci-lint 'v1.33', using 'v1.33.0', calculation took 226ms
    Installing golangci-lint v1.33.0...
    Downloading https://github.com/golangci/golangci-lint/releases/download/v1.33.0/golangci-lint-1.33.0-linux-amd64.tar.gz ...
    Received 92009212 of 92009212 (100.0%), 146.0 MBs/sec
    Cache Size: ~88 MB (92009212 B)
    /bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/1fe13742-cdde-4fcd-88d4-a1bcad1244b3/cache.tzst -P -C /home/runner/work/evcc/evcc
    /bin/tar xz --warning=no-unknown-keyword -C /home/runner -f /home/runner/work/_temp/11aa6afa-628a-4b5d-94a5-40d55abea5bd
    Error: /bin/tar: ../../../go/pkg/mod/gopkg.in/ini.v1@v1.62.0/ini.go: Cannot open: File exists
    Error: /bin/tar: ../../../go/pkg/mod/gopkg.in/ini.v1@v1.62.0/bench_test.go: Cannot open: File exists
    ...
    Error: /bin/tar: ../../../go/pkg/mod/golang.org/x/mod@v0.3.0/modfile/rule.go: Cannot open: File exists
    Error: /bin/tar: ../../../go/pkg/mod/golang.org/x/mod@v0.3.0/modfile/print.go: Cannot open: File exists
    /bin/tar: Exiting with failure status due to previous errors
    Warning: Tar failed with error: The process '/bin/tar' failed with exit code 2
    Prepared env in 3125ms

**Comment by dahu33** [comment]
I have the same issue.

**Comment by h4yfans** [comment]
Same!

**Comment by phillbaker** [comment]
Perhaps `installLint` should return early if the install path already exists?

https://github.com/golangci/golangci-lint-action/blob/54a84d46fb7183443c869b1b7d0dc34f640fcfd7/src/run.ts#L19

**Comment by nicovogelaar** [comment]
A workaround is to run this before:
```shell
go clean -modcache
```

**Comment by andig** [comment]
Thats not acceptable imho. The expectation of finding a clean modcache is wrong.

**Comment by NomNes** [comment]
I have the same issue, but only on self-hosted runner

**Comment by gabizou** [comment]
I'm running into this issue after having something like this as a run file (using protoc to generate models)
```yaml
name: "golangci-lint report"
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.15
            -   name: Install Protoc
                uses: arduino/setup-protoc@v1
                with:
                    version: '3.14'
            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: |
                        .go/cache
                        ./gen
                    key: ${{ runner.os }}-${{ hashFiles('./go.mod') }}
            -   name: Add protoc to path
                run: |
                    echo "$GOPATH"
                    echo "$GOPATH/bin" >> $GITHUB_PATH
                    echo "$PATH"
                    go get -u github.com/golang/protobuf/protoc-gen-go
            -   name: Setup generated code
                run: |
                    make setup
            -   name: golangci-lint
                uses: golangci/golangci-lint-action@v2
                with:
                    # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
                    version: v1.34
                    args: -v --timeout=5m

```
The trouble is that our makefile does set up  the code generation with both `go generate` and `protoc`. Any advice? I'm struggling to find a happy medium for having code generation and linting in actions.

**Comment by andig** [comment]
It seems the issue has been around for some time and accepted as being an issue with the linter action: linter expects module cache as clean which is not reasonable. Workarounds like cleaning the module cache appear undesirable regarding performance.

Is there anything missing in terms of transparency or input to move this into fixing?

**Comment by SVilgelm** [comment]
The issue should be fixed by #156 , but there is an issue with macOs

**Comment by steebchen** [comment]
Thanks to all fixing this!

**Comment by SVilgelm** [comment]
It's released in v2.4.1

**Comment by andig** [comment]
I'm still seeing these errors using `golangci/golangci-lint-action@v2`. Do I need to upgrade my build in any way?

**Comment by kprav33n** [comment]
I tried v2.4.1 and it doesn't seem to fix the issue for me.

Here is my configuration

```yaml
name: Code sanity
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - wip
  pull_request:
jobs:
  default:
    name: Code sanity
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Install protobuf compiler
        run: sudo apt-get install protobuf-compiler
      - name: Install protobuf and grpc generators
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - name: Generate protobuf and grpc bindings
        run: go generate
      - name: Run linting
        uses: golangci/golangci-lint-action@v2.4.1
        with:
          version: v1.37.1
```

Here is a snippet from the log.

```
Run golangci/golangci-lint-action@v2.4.1
  with:
    version: v1.37.1
    github-token: ***
    only-new-issues: false
    skip-go-installation: false
    skip-pkg-cache: false
    skip-build-cache: false
  env:
    GOROOT: /opt/hostedtoolcache/go/1.15.8/x64
prepare environment
  Finding needed golangci-lint version...
  Setup go stable version spec 1
  Found in cache @ /opt/hostedtoolcache/go/1.16.0/x64
  Added go to the path
  Installing golangci-lint v1.37.1...
  Downloading https://github.com/golangci/golangci-lint/releases/download/v1.37.1/golangci-lint-1.37.1-linux-amd64.tar.gz ...
  Successfully setup go version 1
  go version go1.16 linux/amd64
  
go env
  GO111MODULE=""
  GOARCH="amd64"
  GOBIN=""
  GOCACHE="/home/runner/.cache/go-build"
  GOENV="/home/runner/.config/go/env"
  GOEXE=""
  GOFLAGS=""
  GOHOSTARCH="amd64"
  GOHOSTOS="linux"
  GOINSECURE=""
  GOMODCACHE="/home/runner/go/pkg/mod"
  GONOPROXY=""
  GONOSUMDB=""
  GOOS="linux"
  GOPATH="/home/runner/go"
  GOPRIVATE=""
  GOPROXY="https://proxy.golang.org,direct"
  GOROOT="/opt/hostedtoolcache/go/1.16.0/x64"
  GOSUMDB="sum.golang.org"
  GOTMPDIR=""
  GOTOOLDIR="/opt/hostedtoolcache/go/1.16.0/x64/pkg/tool/linux_amd64"
  GOVCS=""
  GOVERSION="go1.16"
  GCCGO="gccgo"
  AR="ar"
  CC="gcc"
  CXX="g++"
  CGO_ENABLED="1"
  GOMOD="/home/runner/work/mapreduce/mapreduce/go.mod"
  CGO_CFLAGS="-g -O2"
  CGO_CPPFLAGS=""
  CGO_CXXFLAGS="-g -O2"
  CGO_FFLAGS="-g -O2"
  CGO_LDFLAGS="-g -O2"
  PKG_CONFIG="pkg-config"
  GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3333635328=/tmp/go-build -gno-record-gcc-switches"
  
Installed Go in 168ms
/usr/bin/tar xz --overwrite --warning=no-unknown-keyword -C /home/runner -f /home/runner/work/_temp/811fb309-b7a1-454a-a264-8d123d4b2c16
Installed golangci-lint into /home/runner/golangci-lint-1.37.1-linux-amd64/golangci-lint in 798ms
Received 69036137 of 69036137 (100.0%), 73.4 MBs/sec
Cache Size: ~66 MB (69036137 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/e5fbd38b-6100-403b-884c-492880e5f9c7/cache.tzst -P -C /home/runner/work/mapreduce/mapreduce
Error: /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/integration_test.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/regenerate.bash: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/AUTHORS: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/release.bash: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/.gitignore: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/go.mod: Cannot open: File exists
```

**Comment by andig** [comment]
Same here using @v2

**Comment by kprav33n** [comment]
As a workaround, I'm forcing the action not to use pkg cache. This solves my issue for now.

```yaml
      - name: Run linting
        uses: golangci/golangci-lint-action@v2.4.1
        with:
          version: v1.38
          skip-go-installation: true
          skip-pkg-cache: true
```

**Comment by steebchen** [comment]
I can also confirm that the issue is not solved yet, most likely due to the second invocation of tar.

@SVilgelm Can we please re-open this issue? Thanks.

**Comment by lukehinds** [comment]
+ 1 experiencing the same issue.

**Comment by JakeCooper** [comment]
Also seeing this

https://github.com/railwayapp/cli/pull/76/checks?check_run_id=2223743157

**Comment by andig** [comment]
Seems due to #221 and should hopefully be fixed now

**Comment by sk-** [comment]
This issue does not seem to be resolved. We are using v3 and we still have the cache issue even though we see that the tar command is being invoked with the `--overwrite` flag.

```
/usr/bin/tar xz --overwrite --warning=no-unknown-keyword --overwrite -C /home/runner -f /home/runner/work/_temp/e28805ed-42c7-4d53-aa78-baf19cfab942
```

**Comment by andig** [comment]
It would be nice to reopen this:

- issue still exists
- I have a lint task that uses caching and takes 17s- probably largely due to writing 24k of error messages (https://github.com/evcc-io/evcc/runs/7614283087?check_suite_focus=true)

**Comment by seb-mtl** [comment]
Hey there, me and our self-hosted runner join the hall of error log recipients. Happy to share more info to help fixing the bug if needed.

```
  Error: /usr/bin/tar: ../../../../go/pkg/mod/github.com/spf13/cobra@v1.5.0/args_test.go: Cannot open: File exists
  /usr/bin/tar: ../../../../go/pkg/mod/github.com/spf13/cobra@v1.5.0/.github/workflows/stale.yml: Cannot open: File exists
  /usr/bin/tar: ../../../../go/pkg/mod/github.com/spf13/cobra@v1.5.0/.github/workflows/labeler.yml: Cannot open: File exists
  /usr/bin/tar: ../../../../go/pkg/mod/github.com/spf13/cobra@v1.5.0/.github/workflows/size-labeler.yml: Cannot open: File exists
  /usr/bin/tar: ../../../../go/pkg/mod/github.com/spf13/cobra@v1.5.0/.github/workflows/test.yml: Cannot open: File exists
  /usr/bin/tar: ../../../../go/pkg/mod/github.com/spf13/cobra@v1.5.0/.github/dependabot.yml: Cannot open: File exists
  /usr/bin/tar: ../../../../go/pkg/mod/github.com/spf13/cobra@v1.5.0/.github/labeler.yml: Cannot open: File exists
  /usr/bin/tar: ../../../../go/pkg/mod/github.com/spf13/cobra@v1.5.0/MAINTAINERS: Cannot open: File exists
  /usr/bin/tar: ../../../../go/pkg/mod/github.com/spf13/cobra@v1.5.0/.golangci.yml: Cannot open: File exists
  /usr/bin/tar: ../../../../go/pkg/mod/github.com/spf13/cobra@v1.5.0/README.md: Cannot open: File exists
```

**Comment by ludusrusso** [comment]
Same here

**Comment by sj14** [comment]
Setting `skip-cache` to `true` worked for me.

**Comment by andig** [comment]
> Setting skip-cache to true worked for me.

Of course but it just generates another slow-down...

**Comment by OmegaRogue** [comment]
I'm also encountering this problem, and skipping cache is not an option for me, as I have a large cgo dependency in my codebase, which adds about 30 minutes to the workflow run time if its not being cached. This is my workflow: https://github.com/OmegaRogue/weylus-desktop/blob/main/.github/workflows/golangci-lint.yml

**Comment by andig** [comment]
@ldez any chance to reopen this issue? It's really not fixed, only has an ugly workaround.

**Comment by andig** [comment]
Thank you, much appreciated.

If anyhow possible, the desired behaviour would be overwriting the target files without error. Potentially adding a `overwrite: true` option to the action config.

**Comment by ldez** [comment]
I'm reopening but don't put hope on me for the fix: I have already enough work with the main repo and I don't use this GitHub Action.
So I hope that somebody will create a PR for fixing that.

**Comment by OmegaRogue** [comment]
I'm also encountering this problem, and skipping cache is not an option for me, as I have a large cgo dependency in my codebase, which adds about 30 minutes to the workflow run time if its not being cached. This is my workflow: https://github.com/OmegaRogue/weylus-desktop/blob/main/.github/workflows/golangci-lint.yml

**Comment by andig** [comment]
Since https://github.com/golangci/golangci-lint-action/pull/156 was merged (which adds `--overwrite`), why are we still seeing this? Permissions issue?

/cc @stmcginnis

**Comment by OmegaRogue** [comment]
I'm testing that idea right now, otherwise, I might have to dust off my actions script that gives me ssh access and manually debug...

**Comment by OmegaRogue** [comment]
so, for this error:
```
  Error: /usr/bin/tar: ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/dial.go: Cannot open: File exists
  ```
I decided to investigate things more closely, so i added an `ls -lha ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/dial.go` both before and after running the `golangci-lint-action`.
The `setup-go@v4` action has the input `cache: false`.
Before running the first `ls`, the only go commands that are being run are a `go install` for a codegen binary https://github.com/abice/go-enum and a `go generate`.
The `ls` before the lint action outputs this:
```
Run ls -lha ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/dial.go
  ls -lha ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/dial.go
  shell: /usr/bin/bash -e {0}
  env:
    GO111MODULE: on
    CACHE_KEY: 58ae1a6b844ca19a1c786138c9200473
-r--r--r-- 1 runner docker 7.8K Apr  2 13:47 ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/dial.go
```
The `ls` after the lint action outputs the same thing again:
```
Run ls -lha ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/dial.go
  ls -lha ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/dial.go
  shell: /usr/bin/bash -e {0}
  env:
    GO111MODULE: on
    CACHE_KEY: 58ae1a6b844ca19a1c786138c9200473
    MSYS: winsymlinks:nativestrict
-r--r--r-- 1 runner docker 7.8K Apr  2 13:47 ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/dial.go
```

**Comment by OmegaRogue** [comment]
maybe `--keep-newer-files`, `--keep-old-files` or `--skip-old-files` would be a better fit than `--overwrite`

**Comment by andig** [comment]
It looks as if the added overwrite simply doesn't work?

**Comment by OmegaRogue** [comment]
> It looks as if the added overwrite simply doesn't work?

Yes, because the file is readonly

**Comment by OmegaRogue** [comment]
> maybe `--keep-newer-files`, `--keep-old-files` or `--skip-old-files` would be a better fit than `--overwrite`

Which of these would fit it better?

**Comment by OmegaRogue** [comment]
As a temporary workaround, adding
```
- run: sudo chmod -R +w ../../../go/
```
works fine

**Comment by Thiht** [comment]
I have the same error. Not sure how relevant this is, But in my logs I have:

```
2023-04-06T15:00:31.2146729Z [command]/usr/bin/tar xz --overwrite --warning=no-unknown-keyword --overwrite -C /home/runner -f /home/runner/work/_temp/ec300448-6fd2-423a-87bf-6a0f99e2b6c2
# ...
# works ok
# ...
2023-04-06T15:00:38.5909327Z [command]/usr/bin/tar -xf /home/runner/work/_temp/780bff96-0afe-4bfd-9df5-46f24cca729b/cache.tgz -P -C /home/runner/work/apollo/apollo -z
# ...
# wall of errors
```

As you can see, `--overwrite` is present twice in the `tar xz` command. Following the trail here: https://github.com/golangci/golangci-lint-action/blob/32a046958e2303e582501e378567cdc3256c984c/src/install.ts#L50 it seems like tool-cache adds the `--overwrite` itself with GNU tar: https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/tool-cache/src/tool-cache.ts#L275

The call to `tar -xf` however doesn't have `--overwrite`, but I'm not sure where it's made.

**Comment by andig** [comment]
Seems like #156 doesn‘t do what it thinks its doing?

**Comment by Thiht** [comment]
Yes I think #156 doesn't do anything unfortunately :( 
If anyone can find where the `/usr/bin/tar -xf` is called, that'd probably be the correct place

**Comment by stmcginnis** [comment]
Sorry, it's been a long time since I've looked at this, and I've been away from it long enough to not remember a lot of the details.

It looks like there are several issues out there talking about this, but a lot of them point back to the [action toolkit](https://github.com/actions/toolkit/pull/717) being the right place to fix this, and not in `golangci-lint` itself.

**Comment by Thiht** [comment]
After a bit of investigation I found this piece of code in the action toolkit:

[extractTar](https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/cache/src/internal/tar.ts#L280) -> [getCommands](https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/cache/src/internal/tar.ts#L136) -> [getTarArgs](https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/cache/src/internal/tar.ts#L90-L99)

I'm not sure why this `extractTar` function is called from golangci-lint (directly or indirectly) however.

**Comment by Thiht** [comment]
I think I got it.

The [extractTar](https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/cache/src/internal/tar.ts#L280) without the `--overwrite` is called by [@actions/cache - restoreCache](https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/cache/src/cache.ts#L132)

So in the end we got:

In golangci-lint-action:
- The function [`prepareEnv`](https://github.com/golangci/golangci-lint-action/blob/32a046958e2303e582501e378567cdc3256c984c/src/run.ts#L82) is called in [`run`](https://github.com/golangci/golangci-lint-action/blob/32a046958e2303e582501e378567cdc3256c984c/src/run.ts#L186), I guess that's the action startup
- The "first tar" is made by the [`prepareLint`](https://github.com/golangci/golangci-lint-action/blob/32a046958e2303e582501e378567cdc3256c984c/src/run.ts#L87) call in `prepareEnv`
- The "second tar" is made by [`restoreCache`](https://github.com/golangci/golangci-lint-action/blob/32a046958e2303e582501e378567cdc3256c984c/src/run.ts#L86) in `prepareEnv`
- Both of these are promises so I guess the output order is not necessarily consistent

I'm not sure what has to be done to fix the issue. Maybe `--skip-pkg-cache` is actually the correct thing to do. Or maybe we can ask `@actions/cache` to add the `--overwrite` to make restoreCache idempotent

**Comment by ldez** [comment]
I was working on another feature, and as a side effect, I think I find a fix
I'm not sure so I need a tester, who wants to test it?

**Comment by andig** [comment]
I an no longer seeing this problem after I've started disabling the Go action cache when installing Go. This seems fine performance-wise as the lint action does its own caching. I cannot say if this has side effects since my lint job does nothing else, i.e. no binary build.

**Comment by barrettj12** [comment]
I'm still seeing this issue. I'm using the `cache: false` option to `actions/setup-go` so that's not the issue. In our case (very large repo) this causes 50000 lines of error messages, polluting the output log.


https://github.com/barrettj12/juju/actions/runs/5409238605/jobs/9829133078

**Comment by seh** [comment]
Likewise. As @barrettj12 reports, disabling use of the cache by a preceding _actions/setup-go_ workflow step does not alleviate this problem for me.

**Comment by rafapaulin** [comment]
this is still happening on v4 :(

**Comment by kyrylo** [comment]
Same, I installed golangci-lint-action in a fresh project, and my `run` doesn't work.

This project in its current state is not usable for me, unfortunately 😕

![x · kyrylo@1473ccd 2024-03-26 09-43-34](https://github.com/golangci/golangci-lint-action/assets/1079123/638026ca-8914-405d-ab75-87ad77a540bd)

**Comment by siburny** [comment]
It appears there is some confusion regarding this issue. There are two different TAR executions that happen during the run:
one that untars the packages and build cache and one that untars the `golangci-lint` itself. While the latter one was indeed fixed to include the `--overwrite` the parameter, the former wasn't. This is because they use two different caching packages: `@actions/cache` and `@actions/tool-cache` respectively. 

I created a PR to fix `@actions/cache` package to overwrite the files as well: https://github.com/actions/toolkit/pull/1704

**Comment by ldez** [comment]
FYI the caches related to modules and Go build has been removed: #1029

**Comment by ldez** [comment]
The problem was related to Go modules cache, we stopped caching those elements, so the problem should be fixed now.

**Comment by Yarden-Vega** [comment]
Hi, I still have that problem.
I update my CI to go 1.23 and it stopped work :(

```
Run golangci/golangci-lint-action@v3
  with:
    version: v1.60.[2]()
    working-directory: services/go
    only-new-issues: false
    args: --timeout=10m
    install-mode: goinstall
    github-token: ***
    skip-cache: false
    skip-pkg-cache: false
    skip-build-cache: false
prepare environment
  Checking for go.mod: services/go/go.mod
  Received 209715200 of 802086096 (26.1%), 199.6 MBs/sec
  Received 478150656 of 802086096 (59.6%), 227.4 MBs/sec
  Received 7[3](8197504 of 802086096 (92.0%), 23[4]().0 MBs/sec
  Cache Size: ~765 MB (802086096 B)
  /usr/bin/tar -xf /home/runner/work/_temp/ec4f[5]ddd-6921-483f-9e96-4e7e5d52b0[6]e/cache.tzst -P -C /home/runner/work/ --use-compress-program unzstd
  Received [8]02086096 of 8020860[9]()6 (100.0%), 190.8 MBs/sec
  Error: /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/telemetry/config@v0.29.0/doc.go: Cannot open: File exists
  /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/telemetry/config@v0.29.0/LICENSE: Cannot open: File exists
  /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/telemetry/config@v0.29.0/config.json: Cannot open: File exists
  /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/telemetry/config@v0.29.0/go.mod: Cannot open: File exists
  /usr/bin/tar: Exiting with failure status due to previous errors
  Warning: Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
```
