### ISSUE TITLE
"File exists" errors when un-taring golangci-lint

### ISSUE THREAD

**Issue by andig** [golangci/golangci-lint-action#244]
Follow-up to https://github.com/golangci/golangci-lint-action/issues/135, https://github.com/golangci/golangci-lint-action/pull/156 and #221.

Using v2, I'm still seeing these errors:

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.37

Example is in https://github.com/andig/evcc/pull/1075/checks?check_run_id=2655591730

Apart from fixing using `tar`- why not just use `go install` instead?

**Comment by andig** [comment]
Looking at https://pipelines.actions.githubusercontent.com/D1tYAQGUpNaqlpNKaplcT4IVn3rJSlK5kNFys0tSrNSiqbBdeP/_apis/pipelines/1/runs/3119/signedlogcontent/4?urlExpires=2021-05-24T11%3A43%3A31.7174061Z&urlSigningMethod=HMACV1&urlSignature=fl95dXdfFb1YndQYp1OdBV8sg4IEP%2Fdu9Jw4VQz1%2B8c%3D I'm a bit confused what is really going on here:

```
2021-05-24T11:30:59.9592849Z Requested golangci-lint 'v1.37', using 'v1.37.1', calculation took 101ms
2021-05-24T11:30:59.9593619Z Installing golangci-lint v1.37.1...
2021-05-24T11:30:59.9594890Z Downloading https://github.com/golangci/golangci-lint/releases/download/v1.37.1/golangci-lint-1.37.1-linux-amd64.tar.gz ...
2021-05-24T11:30:59.9604130Z [command]/usr/bin/tar xz --overwrite --warning=no-unknown-keyword -C /home/runner -f /home/runner/work/_temp/699e2cb2-9f46-4ed3-ba70-55cf1b855115
2021-05-24T11:30:59.9607159Z Installed golangci-lint into /home/runner/golangci-lint-1.37.1-linux-amd64/golangci-lint in 879ms
2021-05-24T11:30:59.9607999Z Received 50331648 of 370718094 (13.6%), 47.8 MBs/sec
2021-05-24T11:31:00.0583863Z Received 180355072 of 370718094 (48.7%), 85.8 MBs/sec
2021-05-24T11:31:01.0577699Z Received 301989888 of 370718094 (81.5%), 95.9 MBs/sec
2021-05-24T11:31:01.8965434Z Received 370718094 of 370718094 (100.0%), 92.0 MBs/sec
2021-05-24T11:31:01.8967722Z Cache Size: ~354 MB (370718094 B)
2021-05-24T11:31:01.9067971Z [command]/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/ce838b4c-e0e7-4371-b6a5-e0bbc5c6235e/cache.tzst -P -C /home/runner/work/evcc/evcc
2021-05-24T11:31:02.8551876Z /usr/bin/tar: ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/.gitignore: Cannot open: File exists
2021-05-24T11:31:02.8562145Z ##[error]/usr/bin/tar: ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/conn.go: Cannot open: File exists
2021-05-24T11:31:02.8575744Z ##[error]/usr/bin/tar: ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/examples/echo/server.go: Cannot open: File exists
2021-05-24T11:31:02.8578177Z ##[error]/usr/bin/tar: ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/examples/echo/main.go: Cannot open: File exists
2021-05-24T11:31:02.8580108Z /usr/bin/tar: ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/examples/echo/README.md: Cannot open: File exists
2021-05-24T11:31:02.8581576Z ##[error]/usr/bin/tar: ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/examples/echo/server_test.go: Cannot open: File exists
2021-05-24T11:31:02.8583504Z /usr/bin/tar: ../../../go/pkg/mod/nhooyr.io/websocket@v1.8.7/examples/README.md: Cannot open: File exists
```

It seems that the install actually went fine but there's a follow-on step that breaks?

**Comment by seh** [comment]
I see similar errors why I try to use this action. Here's a sample of the first two complaints:
```
  /usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/154ee373-4600-4395-b547-3643dff1d28a/cache.tzst -P -C /home/runner/work/my-repo/my-repo
  Error: /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/grpc@v1.37.0/attributes/attributes_test.go: Cannot open: File exists
```

**Comment by seh** [comment]
Related issues: #23, #135

**Comment by andig** [comment]
@maintainers: any chance to get this fixed? Has a number of past and current related issues.

**Comment by seh** [comment]
I see previous discussion about not running certain Go toolchain commands ahead of _golangci-lint_ in the same GitHub Actions job. In my case, the only thing I run before this action is _go list -find -json ./..._ in order to ensure that there are actually some Go files available on the current branch. If I try to run _golangci-lint_ when there are no Go files available, it fails, instead of succeeding trivially. When _go list_ either produces no output or its "GoFiles" object field has no entries, I skip running _golangci-lint_.

**Comment by seh** [comment]
Oh, I just noticed that this action runs _actions/setup-go_ itself. I was taking care of that myself before running this action, because I need to run _go list_ first as [explained earlier](https://github.com/golangci/golangci-lint-action/issues/244#issuecomment-858617392).

Is it possible to influence which version of Go this action installs? I don't see mention of such a parameter in [the _action.yaml_ file](https://github.com/golangci/golangci-lint-action/blob/ebc78f9b2fcd19a74da6a693bc1419e3313167a8/action.yml).

**Comment by ifree92** [comment]
As a "very hot" solution I have just disabled package caching:

```
skip-pkg-cache: true
```

**Comment by SVilgelm** [comment]
there is a special `skip-go-installation` parameter to use already installed go
```yaml
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
```

**Comment by SVilgelm** [comment]
> This appears to still be present in v1.42
> 
> My build depends on generated files. As several linters seem to examine the full call tree, they will always fail without the generated content. Creating something of a chicken and egg problem.

you are right, there are several linters that require whole project, like `unused`. In this case you need to generate all files first, then run `golangci-lint`. And I don't see the chicken and egg problem here. Your goal is in checking that code is compilable and is valid. So if you run `go generate` first and if fails, then it is an expected and valid result of a workflow.
if the files were successfully generated, then linter can do its work

**Comment by andig** [comment]
> there is a special `skip-go-installation` parameter to use already installed go
> 
> ```yaml
>       - uses: actions/checkout@v2
>       - uses: actions/setup-go@v2
>       - name: golangci-lint
>         uses: golangci/golangci-lint-action@v2
>         with:
>           version: latest
>           skip-go-installation: true
> ```

In https://github.com/evcc-io/evcc/commit/1557bb03d3108410e146130da94b42abdf58eec7 I've added `skip-go-installation: true`, but build log is still full or errors: https://github.com/evcc-io/evcc/runs/4081084055?check_suite_focus=true, see `Lint` step.

**Comment by andig** [comment]
@sg0hsmt @abennett any chance to look at this issue?

**Comment by SVilgelm** [comment]
I checked the logs, so the linter works fine, no issues at all. The errors are related to usage of cache and I found that you are caching the go folder in another step, so I would recommend you to remove that step, it is not needed: https://github.com/evcc-io/evcc/blob/master/.github/workflows/build.yml#L18-L26

so, your step restores the cache, then you call lint action that tries to restore the cache as well and of course it fails due to the files already exist.

**Comment by andig** [comment]
Thank you for the comment. I still feel this is bad behaviour. 

Use case: My code contained generated files and I'd also like to lint those (might have gotten the templates wrong). I can only generate them when the cache is already populated.
I might also simply chose to run the linter as a later step in the build when the cache would already be populated.

Why does the linter think that it needs to restore the cache? Imho that's not its task and if it's optional behaviour then it would help have control over it?

**Comment by SVilgelm** [comment]
have you tried to disable cache?:
```yaml
          skip-pkg-cache: true
          skip-build-cache: true
```

the action is designed to be run alone first, since you have more advanced usage you need to tweak the action's and linter's configs accordingly

**Comment by andig** [comment]
That leads to:

    Run golangci/golangci-lint-action@v2
    prepare environment
    run golangci-lint
      Running [/home/runner/golangci-lint-1.42.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
      level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
      Error: golangci-lint exit with code 4
      Ran golangci-lint in 76614ms

with the manual caching step before looking like this:


    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.go-version }}-go-

This cache will of course be cold when the `go.sum` changes. 

I've finally moved the linter to a later position after the first build step and then it succeeds.

**Comment by StevenACoffman** [comment]
Why can we not add `--overwrite` to tar?

**Comment by SVilgelm** [comment]
Because it is not our code, we use GitHub cache package

**Comment by StevenACoffman** [comment]
Looks like someone tried to fix this upstream for this very package here: https://github.com/actions/toolkit/pull/717 but that PR was superseded by https://github.com/actions/toolkit/pull/807 which was merged on May 21, 2021.

However, the last release of [`actions/cache`](https://www.npmjs.com/package/@actions/cache) was 1.0.7 which was Tuesday, April 13, 2021, prior to the merge of the fix.

As a result, this will not be fixed until a new upstream release is cut and this updates to use it, but no other code needs to be changed.

**Comment by johejo** [comment]
actions/cache has been updated.
https://github.com/golangci/golangci-lint-action/commit/4ef1b2ec49b85244db5924ab1ba5ee23540201fe

Will the v2.5.3 release fix this issue?

**Comment by asarkar** [comment]
I'm seeing similar errors on a third-party library [go-fakeio](https://github.com/rhysd/go-fakeio):
The project is private, so, no point putting a link to the build logs.
```
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/e86bf43d-e4ea-4138-af7c-f2b894b6c32c/cache.tzst -P -C /home/runner/work/google-golang/google-golang
/usr/bin/tar: ../../../go/pkg/mod/github.com/rhysd/go-fakeio@v1.0.0/LICENSE.txt: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/rhysd/go-fakeio@v1.0.0/fakeio.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/rhysd/go-fakeio@v1.0.0/.travis.yml: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/rhysd/go-fakeio@v1.0.0/example/example_test.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/rhysd/go-fakeio@v1.0.0/doc.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/rhysd/go-fakeio@v1.0.0/fakeio_test.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/rhysd/go-fakeio@v1.0.0/README.md: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/github.com/rhysd/go-fakeio@v1.0.0/.appveyor.yml: Cannot open: File exists
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
```

**Comment by StevenACoffman** [comment]
@johejo Yes, see here: https://github.com/golangci/golangci-lint-action/blob/ee1123f13095e65bb81bad3c572e9c1d30f58a52/package.json#L29 

As soon as @SVilgelm , @sayboras or one of the other maintainers cuts a new 2.5.3 release then this issue will be fixed. However, the release may be waiting for some other work.

**Comment by regiszanandrea** [comment]
Hi,

When we'll have this issue fixed by a new release ? 

@SVilgelm @sayboras

**Comment by christophermichaelthomasmillar** [comment]
@SVilgelm , @sayboras when will we have another release. We are seeing this issue as well.

**Comment by StevenACoffman** [comment]
This should be resolved by upgrading to the new v3.0.0 release!

**Comment by andig** [comment]
@StevenACoffman I've just upgraded to 3.0 and I'm still seeing this in https://github.com/evcc-io/evcc/runs/5343866024?check_suite_focus=true:

```
Run golangci/golangci-lint-action@v3
[10](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:10)
prepare environment
[11](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:11)
  Finding needed golangci-lint version...
[12](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:12)
  Requested golangci-lint 'latest', using 'v1.44.2', calculation took [13](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:13)5ms
13
  Installing golangci-lint v1.44.2...
[14](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:14)
  Downloading https://github.com/golangci/golangci-lint/releases/download/v1.44.2/golangci-lint-1.44.2-linux-amd64.tar.gz ...
[15](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:15)
  /usr/bin/tar xz --overwrite --warning=no-unknown-keyword --overwrite -C /home/runner -f /home/runner/work/_temp/c6bcc178-2c51-4379-b906-43113d6e[16](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:16)f6
16
  Installed golangci-lint into /home/runner/golangci-lint-1.44.2-linux-amd64/golangci-lint in 531ms
[17](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:17)
  Received 83886080 of 408206632 (20.5%), 79.9 MBs/sec
[18](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:18)
  Received 230686720 of 408206632 (56.5%), 109.8 MBs/sec
[19](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:19)
  Received 373293056 of 408[20](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:20)6632 (91.4%), 118.5 MBs/sec
20
  Received 408206632 of 408206632 (100.0%), 113.1 MBs/sec
[21](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:21)
  Cache Size: ~389 MB (408206632 B)
[22](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:22)
  /usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/45a7e3c2-b450-405d-b8d9-022c29095af0/cache.tzst -P -C /home/runner/work/evcc/evcc
[23](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:23)
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/goleak@v1.1.10/signal_test.go: Cannot open: File exists
[24](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:24)
  /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/goleak@v1.1.10/go.sum: Cannot open: File exists
[25](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:25)
  /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/goleak@v1.1.10/LICENSE: Cannot open: File exists
[26](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:26)
  /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/goleak@v1.1.10/.travis.yml: Cannot open: File exists
[27](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:27)
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/goleak@v1.1.10/leaks_test.go: Cannot open: File exists
[28](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:28)
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/goleak@v1.1.10/tools.go: Cannot open: File exists
[29](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:29)
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/goleak@v1.1.10/testmain_test.go: Cannot open: File exists
[30](https://github.com/evcc-io/evcc/runs/5343897218?check_suite_focus=true#step:11:30)
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/goleak@v1.1.10/leaks.go: Cannot open: File exists
```

Can you please reopen?

**Comment by SVilgelm** [comment]
We cannot do anything within `golangci-lint-action`, since the `@action/cache` lib is maintained by GitHub.
As I can see the `extractTar` function is imported from `internal` package: https://github.com/actions/toolkit/blob/main/packages/cache/src/cache.ts#L5
and the internal implementation does not contain `--overwrite` flag: https://github.com/actions/toolkit/blob/fcb8c4ca798bd0d81a9b07e2f7dffee8397c4707/packages/cache/src/internal/tar.ts#L57-L86

so there is no way to fix the issue within this action, until GitHub Action uses `tar` without `--overwrite` flag.

I would still recommend to disable the golangci-lint's cache in case of using your own cache step:
```yaml
skip-pkg-cache: true
skip-build-cache: true
```
and increase timeout
```yaml
args: --timeout=10m
```

this action creates a cache for 3 folders:
1. `~/.cache/go-build`, can be disabled by setting `skip-build-cache` to `true`
2. `~/go/pkg`, can be disable by setting `skip-pkg-cache` to `true`
3. `.cache/golangci-lint`, cannot be disable, it is the internal cache

**Comment by andig** [comment]
Re-adding these options is the workaround I had used before. My reason for removing them wre the optimistic note above:

> This issue is blocked until https://github.com/golangci/golangci-lint-action/issues/365 is addressed.
> This should be resolved by upgrading to the new v3.0.0 release!

No harm done, fixed by re-adding.

**Comment by StevenACoffman** [comment]
😞 Sorry. Do you see an upstream issue in  https://github.com/actions/toolkit/ we can link to here for tracking since they didn't fully address it?

**Comment by SVilgelm** [comment]
> Re-adding these options is the workaround I had used before.

In my opinion, this is not workaround, this is how it should work in your case.
Here is how it supposed to work if override option is supported:
1. cache is downloaded manually using action/cache step
2. do some work
3. run golangci-lint
4. linter restores the same cache again by overriding
5. linter does its work
6. linter save the cache
7. cache is saved again, because of action/cache step

so, in this scenario the cache will be downloaded twice and the uploaded twice as well

the proper scenario, with disabled cache:
1. cache is downloaded manually using action/cache step
2. do some work
3. run golangci-lint
5. linter does its work
7. cache is saved again, because of action/cache step

in this scenario, the cache is downloaded and uploaded just once

**Comment by drissamri** [comment]
This pops up (again?) in v3

```
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true

      - name: Build
        run: go build ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
```
```
  Error: /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/text@v0.3.7/message/catalog_test.go: Cannot open: File exists
  /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/text@v0.3.7/README.md: Cannot open: File exists
  /usr/bin/tar: Exiting with failure status due to previous errors
  Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
 ```

**Comment by apuzyrevsky** [comment]
> This pops up (again?) in v3
> 
> ```
>       - name: Install Go
>         uses: actions/setup-go@v3
>         with:
>           go-version: '1.18'
>           cache: true
> 
>       - name: Build
>         run: go build ./...
> 
>       - name: Lint
>         uses: golangci/golangci-lint-action@v3
>         with:
>           version: v1.46.2
> ```
> 
> ```
>   Error: /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/text@v0.3.7/message/catalog_test.go: Cannot open: File exists
>   /usr/bin/tar: ../../../go/pkg/mod/golang.org/x/text@v0.3.7/README.md: Cannot open: File exists
>   /usr/bin/tar: Exiting with failure status due to previous errors
>   Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
> ```

Can confirm, I've got the same issue:
` Error: /usr/bin/tar: ../../../../home/runner/go/pkg/mod/github.com/google/renameio@v1.0.1/doc.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../../home/runner/go/pkg/mod/github.com/google/renameio@v1.0.1/example_test.go: Cannot open: File exists`

**Comment by andig** [comment]
It would be nice to reopen this:

- issue still exists
- I have a lint task that uses caching and takes 17s- probably largely due to writing 24k of error messages (https://github.com/evcc-io/evcc/runs/7614283087?check_suite_focus=true)

**Comment by andig** [comment]
> and disable action caching:

Is that still the suggested workaround? Imho, without adding it I'm back to the errors (and apparently slow linting times due to excessive logging) while with adding I'm slow due to the missing lint caches.

**Comment by andig** [comment]
@maintainers could we please reopen? IMHO we have the bad choices of slow CI due to excessive logging or slow CI due do omitting the caches, both are not good options.

**Comment by ldez** [comment]
duplicate of #135
